# Generated by Django 3.0.4 on 2020-04-14 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_auto_20200414_1008'),
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='shipping_address', to='Users.Address'),
        ),
    ]
