# Generated by Django 3.0.4 on 2020-04-16 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_auto_20200414_1147'),
        ('Orders', '0003_auto_20200415_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_orders', to='Users.UserInfo'),
        ),
    ]
