# Generated by Django 3.0.4 on 2020-04-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0004_auto_20200416_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fed_taxes_amount',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='prov_taxes_amount',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal_amount',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=225.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='price_paid',
            field=models.DecimalField(decimal_places=2, default=75.0, max_digits=10),
            preserve_default=False,
        ),
    ]
