# Generated by Django 3.0.4 on 2020-03-26 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.TextField()),
                ('province', models.TextField()),
                ('city', models.TextField()),
                ('street_address', models.TextField()),
                ('postal_code', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Users.Address'),
        ),
    ]
