# Generated by Django 3.0.4 on 2020-03-31 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20200326_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='phone_number',
            field=models.TextField(null=True),
        ),
    ]
