# Generated by Django 3.0.4 on 2020-04-14 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_userinfo_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='address',
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_address', to='Users.UserInfo'),
            preserve_default=False,
        ),
    ]
