# Generated by Django 3.0.4 on 2020-04-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_address_is_default_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='is_default_shipping',
            field=models.BooleanField(default=True),
        ),
    ]
