# Generated by Django 3.0.4 on 2020-04-18 19:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_auto_20200414_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='rating',
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to='Users.UserInfo')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to='Users.UserInfo')),
            ],
        ),
    ]
