# Generated by Django 3.0.4 on 2020-03-24 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
