# Generated by Django 3.0.4 on 2020-04-04 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0003_auto_20200401_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='cart_id',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='user1_id',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='user2_id',
        ),
        migrations.RemoveField(
            model_name='garment',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='glassart',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='jewelry',
            name='product_id',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.RemoveField(
            model_name='order',
            name='buyer_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='seller_id',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='painting',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='sculpture',
            name='product_id',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartProduct',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Garment',
        ),
        migrations.DeleteModel(
            name='GlassArt',
        ),
        migrations.DeleteModel(
            name='Jewelry',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
        migrations.DeleteModel(
            name='Painting',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Sculpture',
        ),
    ]
