# Generated by Django 3.0.4 on 2020-04-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0005_cart_cartproduct_chat_garment_glassart_jewelry_message_order_orderproduct_painting_product_sculpture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
