# Generated by Django 3.0.4 on 2020-04-04 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0006_auto_20200404_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garment',
            name='product_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Market.Product'),
        ),
        migrations.AlterField(
            model_name='glassart',
            name='product_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Market.Product'),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='product_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Market.Product'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='product_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Market.Product'),
        ),
        migrations.AlterField(
            model_name='sculpture',
            name='product_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Market.Product'),
        ),
    ]
