# Generated by Django 3.0.4 on 2020-04-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0007_auto_20200404_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PAINTING', 'Painting'), ('SCULPTURE', 'Sculpture'), ('GARMENT', 'Garment'), ('JEWELRY', 'Jewelry'), ('GLASS_ART', 'GlassArt')], default='PAINTING', max_length=20),
        ),
    ]
