# Generated by Django 3.0.4 on 2020-04-14 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0011_auto_20200404_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
    ]
