# Generated by Django 3.0.3 on 2020-04-15 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0011_auto_20200404_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='user2',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
