# Generated by Django 3.0.3 on 2020-04-16 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0012_auto_20200415_2140'),
        ('Market', '0012_auto_20200413_2016'),
    ]

    operations = [
    ]
